### ISSUE TITLE
Generic support for other libraries

### ISSUE THREAD

**Issue by benmccann** [carbon-design-system/carbon-preprocess-svelte#20]
I ran into the same problem this preprocessor is solving in another library and was just pointed here. Wow. This is a pretty ingenious solution! I couldn't come up with any answer I liked myself

I think it could be recommended for all projects in the SvelteKit FAQ. Possibly it could even be included in SvelteKit by default until / unless another solution is built in

I was wondering, is there anything Carbon-specific about it? Maybe it could be called something more general like `carbon-design-system/fast-imports-preprocessor`?

**Comment by metonym** [comment]
@benmccann I would love to see this be supported by SvelteKit!

> I was wondering, is there anything Carbon-specific about it?

Definitely nothing Carbon-specific, but as @dominikg [alluded to](https://github.com/sveltejs/kit/issues/2612#issuecomment-944926432), a generic approach would probably require some runtime logic.

This preprocessor creates and consumes a [pre-built file ](https://github.com/carbon-design-system/carbon-preprocess-svelte/blob/main/src/build/build-components.ts#L21)that maps the Carbon component to the actual source path.

**Comment by benmccann** [comment]
I'm going to close this since a feature has been added to `vite-plugin-svelte` that removes the need for it: https://github.com/sveltejs/vite-plugin-svelte/pull/200

If that feature doesn't work out as a solution, maybe I'll be back here :smile:
