### ISSUE TITLE
Some styles are lost after optimizeCss()

### ISSUE THREAD

**Issue by rkakrik** [carbon-design-system/carbon-preprocess-svelte#22]
I am using sveltekit with carbon. In dev mode everything is working, but after build with optimizeCss() some styles are lost (h2, SideNavMenu, etc).
Without optimizeCss():
```css
    font-size: 2rem;
    font-weight: 400;
    line-height: 1.25;
    letter-spacing: 0;
```

**Comment by metonym** [comment]
The `optimizeCss` plugin was re-written from scratch in v0.11.

It's designed to only focus on Carbon `.bx--` prefixed styles to minimize false positives.

Docs: https://github.com/carbon-design-system/carbon-preprocess-svelte?tab=readme-ov-file#optimizecss
