### ISSUE TITLE
optimizeCarbonImports breaks sveltekit hydration

### ISSUE THREAD

**Issue by alpap** [carbon-design-system/carbon-preprocess-svelte#23]
I tried to port my app from routify to sveltekit, and I noticed that when I add `optimizeCarbonImports` in the preprocess sectionm of my config the componenets would not hydrate in production but still work normally in local development 

```js
/** @type {import('@sveltejs/kit').Config} */
import { icons, optimizeCss, elements, optimizeCarbonImports } from 'carbon-preprocess-svelte'
import vercel from '@sveltejs/adapter-vercel'

const config = {
  preprocess: [optimizeCarbonImports(),elements(), icons()],
  kit: {
    target: '#svelte',
    ssr: false,
    trailingSlash: 'never',
    vite: {
      plugins: [optimizeCss()],
    },
    adapter: vercel(),
    prerender: {
      enabled: false,
    },
  },
}

export default config
```

**Comment by metonym** [comment]
Commenting for posterity. This library was rewritten in v0.11, but many concepts still apply.

## optimizeImports preprocessor

`optimizeImports` does not perform preprocessing. Additional preprocessing (e.g., TypeScript) should be performed first.

For example, `vitePreprocess` should precede `optimizeImports`.

```js
// svelte.config.js
import adapter from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import { optimizeImports } from "carbon-preprocess-svelte";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [
    // Preprocessors are run in sequence.
    // If using TypeScript, the code must be transpiled first.
    vitePreprocess(),
    optimizeImports(),
  ],
  kit: {
    adapter: adapter(),
  },
};
```

## optimizeCss plugin

The `optimizeCss` plugin was rewritten from scratch. It's sole responsibility is to avoid false positives. This means it's slightly less aggressive in what unused styles it can remove. However, accuracy must be higher.

It was also rewritten as a Vite plugin (meaning it's Rollup compatible) as well as Webpack plugin.

Docs on using it are here: https://github.com/carbon-design-system/carbon-preprocess-svelte?tab=readme-ov-file#optimizecss
