### ISSUE TITLE
HeaderSearch has wrong styling when compiled

### ISSUE THREAD

**Issue by keehun** [carbon-design-system/carbon-preprocess-svelte#24]
I am using a `HeaderSearch` component to include a search bar in my global header bar on top. When running svelte in local development, everything works properly and looks like this:

<img width="675" alt="Screen Shot 2021-12-23 at 2 24 53 PM" src="https://user-images.githubusercontent.com/77378/147288697-172d4aad-bcad-45e4-9383-55914ef66f28.png">

That is the right half of the browser window at the top of the page. Here it is expanded:
<img width="675" alt="Screen Shot 2021-12-23 at 2 25 34 PM" src="https://user-images.githubusercontent.com/77378/147288757-d766ff71-fe49-4f76-acbe-047c28f39081.png">

When I use `npm run build` and host it on Netlify, the `HeaderSearch` component is missing quite a few styles and looks like this:
<img width="679" alt="Screen Shot 2021-12-23 at 2 30 44 PM" src="https://user-images.githubusercontent.com/77378/147289119-e9a15aae-0005-401c-8bd9-7758dcbea4c0.png">

And here it is extended:
<img width="683" alt="Screen Shot 2021-12-23 at 2 31 08 PM" src="https://user-images.githubusercontent.com/77378/147289161-1f754bf8-81b5-45ed-a9c3-257ef2ae6b88.png">

I had run into a few, other minor differences between local & prod before, but nothing like this. Maybe something is not configured properly? I would love some pointers to figure out what's causing the differences here.

**Comment by metonym** [comment]
I rewrote this library from scratch in [v0.11.0](https://github.com/carbon-design-system/carbon-preprocess-svelte/releases/tag/v0.11.0), specifically focusing on getting the `optimizeCss` plugin to a good state.

`optimizeCss` is now a plain Vite plugin, meaning it should work with SvelteKit/Astro/Vite. Additionally, it's compatible with Rollup. The library also ships a plugin for Webpack users.

I specifically tested the plugin with the UI Shell examples – this required some additional legwork (https://github.com/carbon-design-system/carbon-components-svelte/pull/1940)

- [README docs](https://github.com/carbon-design-system/carbon-preprocess-svelte?tab=readme-ov-file#sveltekit-1)
- [Full example](https://github.com/carbon-design-system/carbon-preprocess-svelte/tree/main/examples/sveltekit)

Essentially, a SvelteKit config might look like:

```js
// vite.config.js
import { sveltekit } from "@sveltejs/kit/vite";
import { optimizeCss } from "carbon-preprocess-svelte";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [sveltekit(), optimizeCss()],
});
```
