### ISSUE TITLE
optimizeCss removes carbon-charts css 

### ISSUE THREAD

**Issue by halindraprakoso** [carbon-design-system/carbon-preprocess-svelte#26]
Hello,
I tried carbon-charts and wondered why it had missing css even though I imported the css file. It turns out that it was caused by optimizeCss(). Nevertheless, I can work around it by importing stylesheet from html head.

**Comment by johannesmutter** [comment]
I experience the same issue. Not only does optimizeCss remove carbon-charts styles (in my case the legend), but it also removes the search bar styles of the UI shell and any custom css in custom components unless they are wrapped with a :global() tag.

Using:
		"@carbon/charts-svelte": "^0.55.1",
		"carbon-components-svelte": "^0.61.1",
		"carbon-preprocess-svelte": "^0.6.0",
		"sass": "^1.49.7",
		"svelte": "^3.46.4",
		"svelte-preprocess": "^4.10.2"
		"postcss": "^8.4.6",

**Comment by arjunindia** [comment]
I am also having the same issue.
