### ISSUE TITLE
`optimizeImports` incompatible with Carbon icons v11

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-preprocess-svelte#33]
Named imports are no longer resolved correctly with the structure of v11.

E.g.

```js
import { BrightnessContrast, Tools, ... } from 'carbon-icons-svelte';
```

Results in errors like:
> Module not found: Error: Can't resolve 'carbon-icons-svelte/lib/BrightnessContrast/BrightnessContrast.svelte' in '...'

(The same thing happens for `optimizeCarbonImports` from `'carbon-components-svelte/preprocess'`)

**Comment by metonym** [comment]
This should support it but it's not released: https://github.com/carbon-design-system/carbon-preprocess-svelte/pull/32

**Comment by metonym** [comment]
`carbon-icons-svelte` version 11 is now supported in [v0.8.0](https://github.com/carbon-design-system/carbon-preprocess-svelte/releases/tag/v0.8.0).

**Comment by brunnerh** [comment]
@metonym This currently does not work for me because the code that determines the version makes an assumption which does not always hold.

In [`utils.ts`](https://github.com/carbon-design-system/carbon-preprocess-svelte/blob/811d294498008f1ff415a9d1b671e8bc6e105fa8/src/utils.ts) the function `getPackageJson` looks for the `package.json` only in the current working directory when checking the package versions. I have multiple build configurations in separate sub-directories which all implicitly use the packages from the repository root directory (which also contains the `package.json`)<sup>1</sup>. During build the working directory is the directory of the current build file so the versions are not being determined correctly.

Hence the fallback kicks in which uses the `LATEST_MAJOR_VERSION` from [`constants.ts`](https://github.com/carbon-design-system/carbon-preprocess-svelte/blob/811d294498008f1ff415a9d1b671e8bc6e105fa8/src/constants.ts), which is still at `10` for the icons.

<sub><sup>1</sup> If I recall correctly, Node actually uses *all* `node_modules` directories on the way to the root of the file system directory tree.</sub>

**Comment by metonym** [comment]
Nice catch. The latest version for icons is now set to `11` in [v0.8.2](https://github.com/carbon-design-system/carbon-preprocess-svelte/releases/tag/v0.8.2)
