### ISSUE TITLE
Svelte 4 compatibility for peer dependencies

### ISSUE THREAD

**Issue by ciscoheat** [carbon-design-system/carbon-preprocess-svelte#48]
I get this message when updating to Svelte 4:

```
WARN Issues with peer dependencies found
.
└─┬ carbon-preprocess-svelte 0.9.1
  └─┬ svelte-preprocess 4.10.7
    └── ✕ unmet peer svelte@^3.23.0: found 4.0.0
```

My svelte-preprocess version in package.json is `^5.0.4`.

**Comment by metonym** [comment]
It seems that the warning comes from `svelte-preprocess`, no?

**Comment by ciscoheat** [comment]
It will probably be fixed by updating that dependency in carbon-preprocess-svelte to ^5.0.0, if it's possible.

**Comment by metonym** [comment]
Understood, thank you for clarifying.
