### ISSUE TITLE
Request fix optimizeImport module support carbon-icon-component v12

### ISSUE THREAD

**Issue by TrungRueta** [carbon-design-system/carbon-preprocess-svelte#49]
Since Svelte 4 was released, carbon-component-svelte was also upgraded a few days ago, I would like to request we upgrade the component to support icon v12.

For now in code only validate package icon prefix v11. When meet v12 it fell to an old icon component link and broken site.

**Comment by metonym** [comment]
Fixed in [v0.10.0](https://github.com/carbon-design-system/carbon-preprocess-svelte/releases/tag/v0.10.0).
