### ISSUE TITLE
[plugin-optimize-css] TypeError: PurgeCSS is not a constructor

### ISSUE THREAD

**Issue by SarcevicAntonio** [carbon-design-system/carbon-preprocess-svelte#6]
Im back :v This time I get the error `PurgeCSS is not a constructor`.

Not sure what that's about but it might be related to https://github.com/FullHuman/purgecss/issues/276 or https://github.com/FullHuman/purgecss/issues/43

```bash
$ npm run build

> cc-webapp@0.0.0 build
> routify -b && svelte-check && vite build

[Routify] Generated routes in 0 ms

Loading svelte-check in workspace: c:\Users\LinkPlay\dev\first-prototype\FrontEnd
Getting Svelte diagnostics...
====================================

====================================
svelte-check found 0 errors, 0 warnings and 0 hints
vite v2.2.4 building for production...
✓ 126 modules transformed.
rendering chunks (13)...[plugin-optimize-css] PurgeCSS is not a constructor
error during build:
TypeError: PurgeCSS is not a constructor
    at Object.generateBundle (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:72991:40)
    at C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\rollup\dist\shared\rollup.js:18918:25
```

Sorry for bringing the next bug. Could also be something wrong with my setup so if you want any configs hit me up.
Cheers 😄

**Comment by metonym** [comment]
Have you tried it with a SvelteKit set-up?

Sharing a config would be helpful.

EDIT: was able to reproduce the error using a basic Rollup set-up

**Comment by metonym** [comment]
@SarcevicAntonio Please give v0.1.0-rc.5 a try. I tested it with a plan Rollup + Svelte set-up that uses the CommonJS bundle.

**Comment by SarcevicAntonio** [comment]
Thanks! It works now 😄 👍  Though the CSS is only marginal smaller:

- Before: 556.77kb / brotli: 40.53kb
- After: 507.81kb / brotli: 38.25kb

but hey, ill take it 😅
