### ISSUE TITLE
optimizeCss({preserveAllIBMFonts: false}) removes all the fonts including the custom ones.

### ISSUE THREAD

**Issue by SLAN14** [carbon-design-system/carbon-preprocess-svelte#65]
When the `preserveAllIBMFonts` is set to `false`, it not only remove the IBM fonts... But also the custom fonts we add in root.css

root.css
`body,
html {
    font-family: "custom-font", sans-serif;
}`

**Current workaround is to set the setting to false.** 
But if the setting removes only IBM fonts, it'll reduce the unnecessary font-faces sent from IBM and will make life easier.

**Comment by metonym** [comment]
Thank you for reporting this. This is fixed in [v0.11.4](https://github.com/carbon-design-system/carbon-preprocess-svelte/releases/tag/v0.11.4).

By default, `preserveAllIBMFonts: false` will not remove non-IBM Plex font rules.
